### ISSUE TITLE
get config/samples/subsamples  as separate function

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pepdbagent#128]
It would be more efficient to retrieve the configuration, samples, and subsamples separately using dedicated functions. Currently, to obtain the configuration, we must execute the project.get method, which retrieves the entire project. This approach is highly inefficient, particularly for large projects.

**Comment by nsheff** [comment]
I agree with this!

**Comment by khoroshevskyi** [comment]
This issue was fixed in 0.8.0
