### ISSUE TITLE
Return value of `get_anno` function

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pepdbagent#15]
I am not sure the best route to take, but it would be nice to split up some of the `get_anno` functionalities. For example, when I run the following:

```python
>>> db.get_anno(namespace='nfcore')
{
  'demo_rna_pep': 
    {
        'id': 176, 
        'namespace': 'nfcore', 
        'anno_info': {
            'proj_description': None, 
            'n_samples': 5
        }
    }, 
  'demo_rna_derived': {
        'id': 177, 
        'namespace': 'nfcore', 
        'anno_info': {
            'proj_description': None, 
            'n_samples': 5
        }
    }
}
```

it would be nice to only receive the annotation info for the **namespace** rather than a list of annotations for each **project** in a namespace - if that makes sense. In other words, I am proposing that there be **two** functions:

1. `get_project_annotation("nfcore/demo_rna_pep")`

This will return something like:

```python
{
        'id': 177, 
        'namespace': 'nfcore', 
        'anno_info': {
            'proj_description': None, 
            'n_samples': 5
        }
    }
```

2. `get_namespace_annotation("demo")`

This will return something like:

```python
{
  'namespace': 'demo',
  'n_projects': 12,
  'n_samples': 876
}
```

Obviously, some of this might need to be indexed when loading the PEP's into the database. Otherwise, if you are clever with SQL, you might be able to construct a query to do it.

**Comment by Khoroshevskyi** [comment]
There is possibility to retrieve just n_samples from each project, that we can sum it, so I think it's kinda solution. Do you need any other information annotations?
