### ISSUE TITLE
A Database is required to run tests in GitHub actions

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pepdbagent#21]
In order to run our unit tests in GitHub action workflows, we need a database to connect to. I have read a bit into [GitHub action services](https://docs.github.com/en/actions/using-containerized-services/about-service-containers), and I tried to set something up, so that we can spin up a postgres instance while testing. I don't think it necessarily works, however. Im using [act](https://github.com/nektos/act) to test locally.

**I see us having two options:**
1. Host database somewhere else to test against. Maybe we can point at the eventual pephub database
2. Spin up database inside the github action containers.

I'm more partial to option 2 (or other options if there are other options!) Help is very much appreciated here. You can see the action I've got setup so far, here: https://github.com/pepkit/pephub_db/blob/dev_nathan/.github/workflows/pytest.yml

**Comment by Khoroshevskyi** [comment]
solved with mock tests
