### ISSUE TITLE
Adding a "Last Updated" field

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pepdbagent#26]
I think it could be cool to add a "Last Updated" field to the database. I was looking through Docker Hub for some inspiration with PEPHub and I liked the information they were presenting regarding their containers:
![image](https://user-images.githubusercontent.com/41063083/183930718-e73cc197-4877-4544-814e-4715eddc5423.png)

I imagine it would just be a `timestamp` typed column when the PEP is uploaded or updated.

**Comment by Khoroshevskyi** [comment]
We can add this information to the annotation column.

**Comment by Khoroshevskyi** [comment]
Fixed
