### ISSUE TITLE
Adding a "Description" field

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pepdbagent#28]
This might belong in the `anno` column, but for the purposes of pephub and the pephub UI, it would be nice to give people the option to add a description to the PEP describing the data it describes (that's odd to think about - very meta). Maybe something about pipelines its compatible with, etc.

Example form:
![image](https://user-images.githubusercontent.com/41063083/186236323-6888efcd-285d-4dec-a839-d902b41c7604.png)

**Comment by Khoroshevskyi** [comment]
you can use it like that
```
conn.upload_project(name="b12321", anno={"description": "..."}
```

And if you want to retrieve this description:
```
get_project_annotation_by_registry(reg="fff")["anno_info"]["description"]

```
Thoughts: 
We can create new class that will work only with annotations, so It will be easier to change everything there and retrieve the data

**Comment by Khoroshevskyi** [comment]
Fixed

**Comment by nleroy917** [comment]
Fantastic
