### ISSUE TITLE
Default database name in `Connection.__init__` is inconsistent with the `.sql` schema file

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pepdbagent#29]
I'm testing the latest changes locally with `pephub` and I noticed that in the constructor method for `Connection`, the default value for `database` is `pep-db`, but the Dockerfile for the database [has "pep-base-sql"](https://github.com/pepkit/pepdbagent/blob/54bc35d8a6991366153f46d87c7e818f31f983f4/pep_db/Dockerfile#L4)

Very minor, but I feel like these should be in sync.

**Comment by Khoroshevskyi** [comment]
You are using old docker file
