### ISSUE TITLE
`User` shouldn't be a required argument

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pepdbagent#48]
I pulled the latest version of `pepdbagent` and I am noticing that when not logged in, a lot of endpoints start failing. The errors usually take a form that looks like this:
```console
TypeError: get_namespace_info() missing 2 required positional arguments: 'user' and 'user_organizations'
```
I think that these should be optional and default to `None`. I envision `pephub`, the majority of the time, will be run **unauthenticated** and thus should be able to elegantly handle cases where a `user` param is not passed in.

I think the fix should be simple as when I manually pass in `None` things seem to work well.

**Comment by nsheff** [comment]
I agree with the idea that `None` would be a sensible default for these kind of things that would be populated when logged in. 

We should expect that things aren't logged in and respond accordingly.
