### ISSUE TITLE
`number_of_projects` and `number_of_samples` in a namespace includes both public and private project counts.

### ISSUE THREAD

**Issue by nleroy917** [pepkit/pepdbagent#64]
### Overview
If you are **unauthenticated** and attempt to fetch information about a particular namespace, the `number_of_samples` and `number_of_projects` information still includes counts from `private` projects.

### An example: 

I have one project with two samples. And it is **private**. Authenticated, I see this. Which is **correct**:
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/41063083/212338867-9d01e664-5e42-4114-9f5d-862253330866.png">

**Unauthenticated** I see this. This is incorrect. It should appear that there are no projects or samples to an unauthenticated user:
![image](https://user-images.githubusercontent.com/41063083/212339560-502fa31c-6de5-4c1b-9c12-41fe6850349a.png)

### Expected behavior
I would expect there to be **no projects or samples** since they are private.

**Comment by Khoroshevskyi** [comment]
This was a problem in previous pepdbagent. I was aware about it. But since we were using two different function to get this information I didn't know where I should change it. 
We won't have this issue in new pepdbagent
