### ISSUE TITLE
Change psycopg2-binary on psycopg2

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pepdbagent#66]
As we deploying pephub and it will have larger amount of users we should change psycopg2-binary on psycopg2 in requirements

**Comment by nleroy917** [comment]
This is biting me right now, and I agree with this!!!

**Comment by Khoroshevskyi** [comment]
oops, I will make minor release tomorrow

**Comment by nleroy917** [comment]
Made a new branch (`master_no_binary`) and am testing it locally with PEPhub and it works great.

**Comment by khoroshevskyi** [comment]
fixed in v0.4.0
