### ISSUE TITLE
Add more efficient index to a description

### ISSUE THREAD

**Issue by khoroshevskyi** [pepkit/pepdbagent#88]
Super fast search if we will ad this index:
CREATE EXTENSION pg_trgm;
CREATE INDEX trgm_index_description ON projects USING gin (description gin_trgm_ops);

https://niallburkley.com/blog/index-columns-for-like-in-postgres/

**Comment by khoroshevskyi** [comment]
Only superuser can add this index.
@khoroshevskyi don't have rights to add it

**Comment by nleroy917** [comment]
I want the PEPhub search to be nearly instant, and right now the SQL-based searches are too slow. They take about 4-5 seconds to complete), so I'll bumpt his

**Comment by nsheff** [comment]
Ok, index created... did that help?

**Comment by khoroshevskyi** [comment]
Yes, now search is very fast. Thank you
